on:
  pull_request:

jobs:
  test-custom-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: simonasbuj/sb-cute-action@v1.0.13
        with:
          milliseconds: 1004
          sb_input: "my secret is very big and very bad"

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.test-action.outputs.time }}"
          echo "${{ steps.test-action.outputs.sb_output }}"